config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :friendships
  resources :members
  # want to list all shortened urls?
  get "/short/:id" => "shortener/shortened_urls#show"
  root "members#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: "Member"
end

app/models/member.rb
# frozen_string_literal: true

require "uri"

class Member < ApplicationRecord
  validate :valid_url?

  after_validation :scrape_headings # once url is valid, start scraping it
  after_save :shorten_website # shorten_website must be after save since relation requires id

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  has_shortened_urls

  private

    def valid_url?
      uri = URI.parse(website)
      unless uri.is_a?(URI::HTTP) && !uri.host.nil?
        errors.add(:website, "#{website} is not a valid url")
      end
    rescue URI::InvalidURIError
      errors.add(:website, "#{website} is not a valid url")
      false
    end

    def shorten_website
      Shortener::ShortenedUrl.generate(website, owner: self)
    end

    def scrape_headings
      ScrapeHeadingsWorker.perform_async(website, id)
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[show edit update destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show; end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit; end

  # POST /friendships
  # POST /friendships.json
  def create
    current_member = Member.find(params[:member_id])
    @friendship = current_member.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    def destroy
      current_member = Member.find(params[:member_id])
      @friendship = current_member.friendships.find(params[:id])
      @friendship.destroy
      flash[:notice] = "Removed friendship."
      redirect_to current_member
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:member_id, :friend_id)
    end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :website)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.number_field :member_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id %>
  </div>

  <div class="field">
    <%= form.label :create %>
    <%= form.text_field :create %>
  </div>

  <div class="field">
    <%= form.label :destroy %>
    <%= form.text_field :destroy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.member_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @friendship.member_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSocialNet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.website %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @member.website %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>